/**
 * @license
 * Copyright (c) 2022 Handsoncode. All rights reserved.
 */

/**
 * This is a class for detailed error messages across HyperFormula.
 */
export class ErrorMessage {
  public static DistinctSigns = '明显的标志。'
  public static WrongArgNumber = '参数数量错误。'
  public static EmptyArg = '空函数参数。'
  public static EmptyArray = '不允许使用空数组。'
  public static ArrayDimensions = '数组维度不兼容。'
  public static NoSpaceForArrayResult = '数组结果没有空间。'
  public static ValueSmall = '值太小。'
  public static ValueLarge = '值太大。'
  public static BadCriterion = '标准不正确。'
  public static RangeManySheets = '范围跨越多个工作表。'
  public static CellRangeExpected = '应为单元格范围。'
  public static WrongDimension = '范围维度错误。'
  public static ScalarExpected = '不允许的单元格范围。'
  public static NumberCoercion = '值不能强制为数字。'
  public static NumberExpected = '需要数字参数。'
  public static IntegerExpected = '值必须是整数。'
  public static BadMode = '无法识别模式。'
  public static DateBounds = '日期超出界限。'
  public static OutOfSheet = '结果引用超出工作表。'
  public static WrongType = '参数类型错误。'
  public static NaN = '遇到NaN或无限值。'
  public static EqualLength = '范围长度必须相等。'
  public static Negative = '值不能为负。'
  public static NotBinary = '字符串不表示二进制数。'
  public static NotOctal = '字符串不表示八进制数。'
  public static NotHex = '字符串不表示十六进制数。'
  public static EndStartPeriod = '结束期间必须至少是开始期间。'
  public static CellRefExpected = '需要单元格引用。'
  public static EmptyRange = '不允许为空范围。'
  public static BadRef = '地址不正确。'
  public static NumberRange = '应为数字范围。'
  public static ValueNotFound = '未找到值。'
  public static ValueBaseLarge = '基数值太大。'
  public static ValueBaseSmall = '基数值太小。'
  public static ValueBaseLong = '基值过长。'
  public static NegativeLength = '长度不能为负数。'
  public static PatternNotFound = '未找到模式。'
  public static OneValue = '至少需要一个值。'
  public static TwoValues = '范围需要包含至少两个元素。'
  public static ThreeValues = '范围至少需要包含三个元素。'
  public static IndexBounds = '索引超出范围。'
  public static IndexLarge = '索引太大。'
  public static Formula = '预期公式。'
  public static NegativeCount = '计数不能为负。'
  public static ParseError = '分析错误。'
  public static SheetRef = '工作表不存在。'
  public static PeriodLong = '周期数不能超过生命长度。'
  public static InvalidDate = '无效日期。'
  public static BitshiftLong = '位移位的结果太长。'
  public static EmptyString = '不允许使用空字符串参数。'
  public static LengthBounds = '长度超出界限。'
  public static NegativeTime = '时间不能为负数。'
  public static NoDefault = '无默认选项。'
  public static Selector = '选择器不能超过参数数。'
  public static StartEndDate = '开始日期必须早于结束日期。'
  public static IncorrectDateTime = '字符串不能表示正确的日期时间。'
  public static CharacterCodeBounds = '字符代码超出范围。'
  public static NonZero = '参数不能为0。'
  public static LessThanOne = '参数不能小于1。'
  public static WeekendString = '不正确的周末位掩码字符串。'
  public static InvalidRoman = '无效的罗马数字。'
  public static WrongOrder = '值的顺序错误。'
  public static ComplexNumberExpected = '需要复数。'
  public static ShouldBeIorJ = '应为 \'i\' 或者 \'j\'。'
  public static SizeMismatch = '数组维度不匹配。'
  public static FunctionName = (arg: string) => `函数名 ${arg} 不能被辨识。`
  public static NamedExpressionName = (arg: string) => `命名表达式 ${arg} 不能被辨识。`
  public static LicenseKey = (arg: string) => `许可证密钥为 ${arg}。`
}
